//! Offline place gazetteer for gallery labeling and search.
//!
//! Bundled data (generated by `luna/scripts/gen_place_data.py`, see
//! `crates/lunad/data/` headers for attribution):
//! - `cities.tsv`    — GeoNames cities15000: name/ascii, coords, region, country
//! - `regions.tsv`   — GeoNames admin1 (state/province) names
//! - `countries.txt` — Natural Earth 110m country polygons, 2dp quantized
//!
//! Runtime cost is small: the tables parse once into a `OnceLock` index; a
//! 1° grid index makes nearest-city lookups touch only a handful of
//! candidates, and country lookups are a bbox prefilter plus ray casting.

use std::collections::HashMap;
use std::sync::OnceLock;

/// Max distance for labeling a photo with a city name and borrowing its
/// admin-1 region (same rule the old 30-city table used).
const CITY_MAX_KM: f64 = 150.0;
/// Fallback country attribution via nearest city when polygons miss
/// (coastal photos just outside a coarse 110m border).
const CITY_COUNTRY_FALLBACK_KM: f64 = 120.0;
/// Query-time radius when a search term resolves to a city.
pub const CITY_QUERY_RADIUS_KM: f64 = 30.0;

const CITIES_TSV: &str = include_str!("../../data/cities.tsv");
const REGIONS_TSV: &str = include_str!("../../data/regions.tsv");
const COUNTRIES_TXT: &str = include_str!("../../data/countries.txt");

#[derive(Debug)]
pub struct City {
    pub lat: f32,
    pub lon: f32,
    pub pop: u32,
    pub name: &'static str,
    pub region: &'static str,
    pub country: &'static str,
}

struct CountryPoly {
    name: &'static str,
    /// min_lat, max_lat, min_lon, max_lon
    bbox: [f32; 4],
    /// All polygon rings flattened; even-odd crossing rule handles holes.
    rings: Vec<Vec<(f32, f32)>>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PlaceKind {
    City,
    Region,
    Country,
}

#[derive(Debug, Clone)]
pub struct PlaceMatch {
    pub kind: PlaceKind,
    /// Canonical name as stored on indexed photo rows.
    pub name: String,
    /// City center (kind == City only).
    pub lat: f64,
    pub lon: f64,
    pub pop: u32,
}

/// What [`Places::enrich`] derives for one GPS coordinate.
#[derive(Debug, Default, Clone)]
pub struct PlaceInfo {
    /// Nearest city within [`CITY_MAX_KM`], else "".
    pub city: &'static str,
    /// Admin-1 (state/province) name via the nearest city, else "".
    pub region: &'static str,
    /// Country via polygon, else nearest city, else "".
    pub country: &'static str,
    /// Display label: city, else region, else country, else raw coords.
    pub label: String,
}

pub struct Places {
    cities: Vec<City>,
    /// 1° grid cell -> city indices.
    grid: HashMap<(i16, i16), Vec<u32>>,
    countries: Vec<CountryPoly>,
    /// Normalized name/alias -> matches.
    lookup: HashMap<String, Vec<PlaceMatch>>,
}

static PLACES: OnceLock<Places> = OnceLock::new();

pub fn index() -> &'static Places {
    PLACES.get_or_init(Places::load)
}

/// Lowercase, fold common accents to ASCII, collapse non-alphanumerics to a
/// single space. Applied to both query phrases and gazetteer keys.
pub fn normalize(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut last_space = true;
    for c in s.chars() {
        for f in fold_char(c).chars() {
            if f.is_ascii_alphanumeric() {
                out.push(f);
                last_space = false;
            } else if !last_space {
                out.push(' ');
                last_space = true;
            }
        }
    }
    if out.ends_with(' ') {
        out.pop();
    }
    out
}

fn fold_char(c: char) -> String {
    let lower: String = c.to_lowercase().collect();
    let mapped: &str = match lower.chars().next().unwrap_or(c) {
        'à' | 'á' | 'â' | 'ã' | 'ä' | 'å' | 'ā' | 'ă' | 'ą' => "a",
        'ç' | 'ć' | 'č' | 'ĉ' | 'ċ' => "c",
        'ď' | 'đ' | 'ð' => "d",
        'è' | 'é' | 'ê' | 'ë' | 'ē' | 'ĕ' | 'ė' | 'ę' | 'ě' => "e",
        'ĝ' | 'ğ' | 'ġ' | 'ģ' => "g",
        'ĥ' | 'ħ' => "h",
        'ì' | 'í' | 'î' | 'ï' | 'ī' | 'ĭ' | 'į' | 'ı' => "i",
        'ĵ' => "j",
        'ķ' => "k",
        'ĺ' | 'ļ' | 'ľ' | 'ŀ' | 'ł' => "l",
        'ñ' | 'ń' | 'ņ' | 'ň' => "n",
        'ò' | 'ó' | 'ô' | 'õ' | 'ö' | 'ø' | 'ō' | 'ŏ' | 'ő' => "o",
        'ŕ' | 'ŗ' | 'ř' => "r",
        'ś' | 'ŝ' | 'ş' | 'š' => "s",
        'ţ' | 'ť' | 'ŧ' => "t",
        'ù' | 'ú' | 'û' | 'ü' | 'ū' | 'ŭ' | 'ů' | 'ű' | 'ų' => "u",
        'ŵ' => "w",
        'ý' | 'ÿ' => "y",
        'ź' | 'ż' | 'ž' => "z",
        'ß' => "ss",
        'æ' => "ae",
        'œ' => "oe",
        'þ' => "th",
        _ => return lower,
    };
    mapped.to_string()
}

/// Common English words that collide with city names — resolving them as
/// places would hijack ordinary queries. Multi-word phrases still resolve.
const AMBIGUOUS_CITY_WORDS: &[&str] = &[
    "nice",
    "bath",
    "reading",
    "derby",
    "mobile",
    "split",
    "june",
    "august",
    "may",
    "march",
    "april",
    "florence",
    "victoria",
    "aurora",
    "dover",
    "clinton",
    "manchester",
    "bright",
    "hurricane",
    "wedding",
    "rose",
    "orange",
];

/// Curated aliases the gazetteer does not carry (abbreviations, exonyms,
/// historical names). Canonical targets must exist in the gazetteer.
const PLACE_ALIASES: &[(&str, &str)] = &[
    ("usa", "United States"),
    ("u s", "United States"),
    ("america", "United States"),
    ("united states of america", "United States"),
    ("uk", "United Kingdom"),
    ("u k", "United Kingdom"),
    ("britain", "United Kingdom"),
    ("great britain", "United Kingdom"),
    ("uae", "United Arab Emirates"),
    ("holland", "Netherlands"),
    ("burma", "Myanmar"),
    ("czech republic", "Czechia"),
    ("ivory coast", "Cote d'Ivoire"),
    ("swaziland", "Eswatini"),
    ("cape verde", "Cabo Verde"),
    ("east timor", "Timor-Leste"),
    ("turkiye", "Turkey"),
    ("dr congo", "Democratic Republic of the Congo"),
    ("drc", "Democratic Republic of the Congo"),
    ("bosnia", "Bosnia and Herzegovina"),
    ("south korea", "South Korea"),
    ("north korea", "North Korea"),
    ("korea", "South Korea"),
    ("nyc", "New York City"),
    ("dc", "Washington"),
    ("vegas", "Las Vegas"),
    ("philly", "Philadelphia"),
    ("saigon", "Ho Chi Minh City"),
    ("bombay", "Mumbai"),
    ("calcutta", "Kolkata"),
    ("peking", "Beijing"),
];

impl Places {
    fn load() -> Places {
        let mut cities = Vec::new();
        let mut lookup: HashMap<String, Vec<PlaceMatch>> = HashMap::new();
        for line in CITIES_TSV.lines() {
            if line.starts_with('#') || line.is_empty() {
                continue;
            }
            let mut f = line.split('\t');
            let (Some(lat), Some(lon), Some(pop)) = (f.next(), f.next(), f.next()) else {
                continue;
            };
            let (Ok(lat), Ok(lon)) = (lat.parse::<f32>(), lon.parse::<f32>()) else {
                continue;
            };
            let pop: u32 = pop.parse().unwrap_or(0);
            let name = f.next().unwrap_or("");
            let ascii = f.next().unwrap_or("");
            let region = f.next().unwrap_or("");
            let country = f.next().unwrap_or("");
            if name.is_empty() {
                continue;
            }
            let m = PlaceMatch {
                kind: PlaceKind::City,
                name: name.to_string(),
                lat: lat as f64,
                lon: lon as f64,
                pop,
            };
            for raw in [name, ascii] {
                let key = normalize(raw);
                if key.len() >= 3 {
                    lookup.entry(key).or_default().push(m.clone());
                }
            }
            cities.push(City {
                lat,
                lon,
                pop,
                name,
                region,
                country,
            });
        }

        let mut grid: HashMap<(i16, i16), Vec<u32>> = HashMap::new();
        for (i, c) in cities.iter().enumerate() {
            grid.entry(cell_of(c.lat as f64, c.lon as f64))
                .or_default()
                .push(i as u32);
        }

        let mut countries = Vec::new();
        for line in COUNTRIES_TXT.lines() {
            if line.starts_with('#') || line.is_empty() {
                continue;
            }
            let mut parts = line.split('|');
            let (Some(name), Some(_iso)) = (parts.next(), parts.next()) else {
                continue;
            };
            let mut bbox = [0f32; 4];
            let mut ok = true;
            for slot in &mut bbox {
                match parts.next().and_then(|v| v.parse().ok()) {
                    Some(v) => *slot = v,
                    None => {
                        ok = false;
                        break;
                    }
                }
            }
            if !ok {
                continue;
            }
            let rings: Vec<Vec<(f32, f32)>> = parts
                .next()
                .unwrap_or("")
                .split(';')
                .filter(|r| !r.is_empty())
                .map(|ring| {
                    ring.split(' ')
                        .filter_map(|pair| {
                            let mut p = pair.split(',');
                            match (p.next()?.parse().ok(), p.next()?.parse().ok()) {
                                (Some(lat), Some(lon)) => Some((lat, lon)),
                                _ => None,
                            }
                        })
                        .collect()
                })
                .filter(|r: &Vec<(f32, f32)>| r.len() >= 4)
                .collect();
            if rings.is_empty() {
                continue;
            }
            countries.push(CountryPoly { name, bbox, rings });
            let key = normalize(name);
            if key.len() >= 3 {
                lookup.entry(key).or_default().push(PlaceMatch {
                    kind: PlaceKind::Country,
                    name: name.to_string(),
                    lat: 0.0,
                    lon: 0.0,
                    pop: u32::MAX,
                });
            }
        }

        for line in REGIONS_TSV.lines() {
            if line.starts_with('#') || line.is_empty() {
                continue;
            }
            let mut f = line.split('\t');
            let (Some(_iso), Some(name), Some(ascii)) = (f.next(), f.next(), f.next()) else {
                continue;
            };
            for raw in [name, ascii] {
                let key = normalize(raw);
                if key.len() >= 3 {
                    lookup.entry(key).or_default().push(PlaceMatch {
                        kind: PlaceKind::Region,
                        name: name.to_string(),
                        lat: 0.0,
                        lon: 0.0,
                        pop: 0,
                    });
                }
            }
        }

        // Aliases resolve to whatever their canonical name already matches.
        for (alias, canonical) in PLACE_ALIASES {
            let canon_key = normalize(canonical);
            if let Some(matches) = lookup.get(&canon_key).cloned() {
                lookup.entry(normalize(alias)).or_default().extend(matches);
            }
        }

        Places {
            cities,
            grid,
            countries,
            lookup,
        }
    }

    /// Gazetteer matches for one normalized phrase.
    pub fn lookup(&self, normalized_phrase: &str) -> &[PlaceMatch] {
        self.lookup
            .get(normalized_phrase)
            .map(|v| v.as_slice())
            .unwrap_or(&[])
    }

    pub fn is_ambiguous_city_word(normalized: &str) -> bool {
        AMBIGUOUS_CITY_WORDS.contains(&normalized)
    }

    fn nearest_city(&self, lat: f64, lon: f64, max_km: f64) -> Option<&City> {
        // GeoNames lists city sections (Paris arrondissements, districts) as
        // plain populated places, so the strictly-nearest candidate can be a
        // sub-city. When a city with 4x+ the population sits within ~8 km,
        // prefer it — that's the name users expect ("Paris", not
        // "Paris 04 Hôtel-de-Ville").
        const DISTRICT_KM: f64 = 8.0;
        const DISTRICT_POP_FACTOR: u32 = 4;
        let dlat = max_km / 111.0;
        let lat_lo = (lat - dlat).max(-90.0);
        let lat_hi = (lat + dlat).min(90.0);
        let km_per_lon = (111.0 * lat.to_radians().cos().abs()).max(15.0);
        let dlon = (max_km / km_per_lon).min(45.0);
        let mut nearest: Option<(&City, f64)> = None;
        let mut biggest_close: Option<&City> = None;
        let clat_lo = lat_lo.floor() as i16;
        let clat_hi = lat_hi.floor() as i16;
        let clon_lo = (lon - dlon).floor() as i32;
        let clon_hi = (lon + dlon).floor() as i32;
        for clat in clat_lo..=clat_hi {
            for clon in clon_lo..=clon_hi {
                let wrapped = (clon + 180).rem_euclid(360) - 180;
                if let Some(idx) = self.grid.get(&(clat, wrapped as i16)) {
                    for &i in idx {
                        let c = &self.cities[i as usize];
                        let d = haversine_km(lat, lon, c.lat as f64, c.lon as f64);
                        if d > max_km {
                            continue;
                        }
                        if nearest.map(|(_, bd)| d < bd).unwrap_or(true) {
                            nearest = Some((c, d));
                        }
                        if d <= DISTRICT_KM && biggest_close.map(|b| c.pop > b.pop).unwrap_or(true)
                        {
                            biggest_close = Some(c);
                        }
                    }
                }
            }
        }
        match (nearest, biggest_close) {
            (Some((n, _)), Some(b)) if b.pop > n.pop.saturating_mul(DISTRICT_POP_FACTOR) => Some(b),
            (Some((n, _)), _) => Some(n),
            (None, _) => None,
        }
    }

    fn country_at(&self, lat: f64, lon: f64) -> Option<&'static str> {
        for c in &self.countries {
            let [min_lat, max_lat, min_lon, max_lon] = c.bbox;
            let la = lat as f32;
            let lo = lon as f32;
            if la < min_lat || la > max_lat || lo < min_lon || lo > max_lon {
                continue;
            }
            if point_in_rings(lon, lat, &c.rings) {
                return Some(c.name);
            }
        }
        None
    }

    /// City/region/country + display label for one coordinate.
    pub fn enrich(&self, lat: f64, lon: f64) -> PlaceInfo {
        let mut country = self.country_at(lat, lon).unwrap_or("");
        if country.is_empty()
            && let Some(c) = self.nearest_city(lat, lon, CITY_COUNTRY_FALLBACK_KM)
        {
            country = c.country;
        }
        // A nearest city across a border must not donate its region/city name.
        let near = match self.nearest_city(lat, lon, CITY_MAX_KM) {
            Some(c) if country.is_empty() || c.country == country => Some(c),
            _ => None,
        };
        let city = near.map(|c| c.name).unwrap_or("");
        let region = near.map(|c| c.region).unwrap_or("");
        let label = if !city.is_empty() {
            city.to_string()
        } else if !region.is_empty() {
            region.to_string()
        } else if !country.is_empty() {
            country.to_string()
        } else {
            format!("{lat:.1}°, {lon:.1}°")
        };
        PlaceInfo {
            city,
            region,
            country,
            label,
        }
    }
}

fn cell_of(lat: f64, lon: f64) -> (i16, i16) {
    (lat.floor() as i16, lon.floor().clamp(-180.0, 179.0) as i16)
}

/// Even-odd crossing rule over every ring; handles holes and multipolygons.
fn point_in_rings(lon: f64, lat: f64, rings: &[Vec<(f32, f32)>]) -> bool {
    let mut inside = false;
    for ring in rings {
        let n = ring.len();
        for i in 0..n {
            let (y1, x1) = (ring[i].0 as f64, ring[i].1 as f64);
            let (y2, x2) = (ring[(i + 1) % n].0 as f64, ring[(i + 1) % n].1 as f64);
            if (y1 > lat) != (y2 > lat) && lon < (x2 - x1) * (lat - y1) / (y2 - y1) + x1 {
                inside = !inside;
            }
        }
    }
    inside
}

pub fn haversine_km(lat1: f64, lon1: f64, lat2: f64, lon2: f64) -> f64 {
    const R: f64 = 6371.0;
    let to_rad = |d: f64| d * std::f64::consts::PI / 180.0;
    let (phi1, phi2) = (to_rad(lat1), to_rad(lat2));
    let d_phi = to_rad(lat2 - lat1);
    let d_lam = to_rad(lon2 - lon1);
    let a = (d_phi / 2.0).sin().powi(2) + phi1.cos() * phi2.cos() * (d_lam / 2.0).sin().powi(2);
    2.0 * R * a.sqrt().asin()
}

/// Label for one coordinate — city, region, country, or raw coords.
pub fn label_for(lat: f64, lon: f64) -> String {
    index().enrich(lat, lon).label
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn normalizes_case_and_accents() {
        assert_eq!(normalize("São Paulo"), "sao paulo");
        assert_eq!(normalize("  New-York "), "new york");
        assert_eq!(normalize("Île-de-France"), "ile de france");
    }

    #[test]
    fn enriches_known_places() {
        let p = index();
        let sea = p.enrich(47.61, -122.33);
        assert_eq!(sea.city, "Seattle");
        assert_eq!(sea.region, "Washington");
        assert_eq!(sea.country, "United States");

        let paris = p.enrich(48.86, 2.35);
        assert_eq!(paris.city, "Paris");
        assert_eq!(paris.country, "France");

        // Rural Oregon: no big city nearby, but the country lands.
        let rural = p.enrich(43.8, -120.5);
        assert_eq!(rural.country, "United States");

        // Open ocean: nothing.
        let ocean = p.enrich(0.0, -140.0);
        assert_eq!(ocean.country, "");
        assert!(ocean.label.contains('°'));
    }

    #[test]
    fn lookup_cities_regions_countries() {
        let p = index();
        assert!(p.lookup("seattle").iter().any(|m| m.name == "Seattle"));
        assert!(p.lookup("oregon").iter().any(|m| m.name == "Oregon"));
        assert!(p.lookup("thailand").iter().any(|m| m.name == "Thailand"));
        assert!(p.lookup("usa").iter().any(|m| m.name == "United States"));
        assert!(
            p.lookup("bosnia")
                .iter()
                .any(|m| m.name == "Bosnia and Herzegovina")
        );
        assert!(p.lookup("sao paulo").iter().any(|m| m.name == "São Paulo"));
    }
}
