// Rotating friendly copy to make idle/loading states feel less sterile.
export const dashboard = [
  "Welcome back. The pigeon is managing operations and snacks, ",
  "Hi there. The mouse intern arrived early and looks determined, ",
  "Hello! The pigeon says today is ‘under control’, ",
  "Welcome! Snack inventory is stable and morale is high, ",
  "Hey there. The seagull was spotted but the pigeon remains calm, ",
  "Welcome back. The raccoon accountant is balancing the snack budget, ",
  "Hello! The pigeon adjusted its clipboard and nodded confidently, ",
  "Welcome! The mouse intern labeled today ‘promising’, ",
  "Hi there. The turtle from HR is observing quietly, ",
  "Welcome back. The pigeon believes this is a good moment to begin, ",

  "Hello! The pigeon reorganized things and feels accomplished, ",
  "Welcome! The snacks are exactly where they should be, ",
  "Hey there. The seagull asked questions. The pigeon declined to answer, ",
  "Welcome back. The raccoon accountant requested a recount, ",
  "Hi there. The mouse intern took notes and added doodles, ",
  "Hello! The pigeon says progress is happening ‘slowly but correctly’, ",
  "Welcome! The owl auditor has not appeared. Everyone is relieved, ",
  "Hey there. The turtle from HR approved today’s tone, ",
  "Welcome back. The pigeon inspected everything twice, ",
  "Hello! Snack morale has been officially acknowledged, ",

  "Welcome! The pigeon filed today under ‘manageable’, ",
  "Hi there. The mouse intern is practicing professionalism, ",
  "Hello! The raccoon accountant says the numbers look ‘friendly’, ",
  "Welcome back. The pigeon is pleased with the level of order, ",
  "Hey there. The seagull is nearby but pretending not to be, ",
  "Welcome! The snacks are resting comfortably, ",
  "Hello! The turtle from HR scheduled nothing urgently, ",
  "Welcome back. The pigeon says this is a safe place to start, ",
  "Hi there. The mouse intern believes in this moment, ",
  "Welcome! The clipboard has been consulted, ",

  "Hello! The pigeon is quietly proud of this setup, ",
  "Welcome back. The raccoon accountant made a note and smirked, ",
  "Hey there. The seagull was denied entry politely, ",
  "Welcome! Snack access remains fair and just, ",
  "Hi there. The turtle from HR nodded approvingly, ",
  "Welcome back. The pigeon says things are aligned, ",
  "Hello! The mouse intern filed something under ‘important’, ",
  "Welcome! The owl auditor remains a rumor, ",
  "Hey there. The pigeon adjusted its tiny tie, ",
  "Welcome back. Order has been gently applied, ",

  "Hello! The pigeon declared this a ‘working atmosphere’, ",
  "Welcome! The snacks are part of the plan, ",
  "Hi there. The raccoon accountant double-checked everything, ",
  "Welcome back. The seagull is waiting outside dramatically, ",
  "Hey there. The mouse intern asked a good question, ",
  "Welcome! The turtle from HR is very calm about everything, ",
  "Hello! The pigeon says clarity is present, ",
  "Welcome back. The clipboard is satisfied, ",
  "Hi there. Snack crumbs indicate recent success, ",
  "Welcome! This feels officially organized, ",

  "Hello! The pigeon believes momentum is building, ",
  "Welcome back. The raccoon accountant approved today’s math, ",
  "Hey there. The seagull attempted eye contact and failed, ",
  "Welcome! The mouse intern labeled this ‘Phase One’, ",
  "Hi there. The turtle from HR remains unbothered, ",
  "Welcome back. The pigeon says things are proceeding nicely, ",
  "Hello! Snack morale is holding steady, ",
  "Welcome! The owl auditor has not requested documentation, ",
  "Hey there. The pigeon marked today as ‘good’, ",
  "Welcome back. Everything is politely arranged, ",

  "Hello! The pigeon trusts this configuration, ",
  "Welcome! The raccoon accountant adjusted the ledger, ",
  "Hi there. The mouse intern is learning quickly, ",
  "Welcome back. The seagull was redirected successfully, ",
  "Hey there. The turtle from HR approved a flexible pace, ",
  "Welcome! Snacks are being treated with respect, ",
  "Hello! The pigeon checked twice and smiled once, ",
  "Welcome back. The clipboard feels important, ",
  "Hi there. This is the calm version of things, ",
  "Welcome! Order is present and comfortable, ",

  "Hello! The pigeon believes today is promising, ",
  "Welcome back. The raccoon accountant counted crumbs, ",
  "Hey there. The seagull is negotiating from afar, ",
  "Welcome! The mouse intern requested mentorship, ",
  "Hi there. The turtle from HR scheduled a check-in eventually, ",
  "Welcome back. The pigeon says everything is fine, ",
  "Hello! Snacks have been acknowledged officially, ",
  "Welcome! The owl auditor remains theoretical, ",
  "Hey there. The clipboard has been updated, ",
  "Welcome back. This is a good place to continue, ",

  "Hello! The pigeon declared this a low-drama moment, ",
  "Welcome! The raccoon accountant nodded knowingly, ",
  "Hi there. The mouse intern is feeling optimistic, ",
  "Welcome back. The seagull has been distracted elsewhere, ",
  "Hey there. The turtle from HR smiled faintly, ",
  "Welcome! Snacks are calm and cooperative, ",
  "Hello! The pigeon says things are aligned enough, ",
  "Welcome back. The clipboard agrees, ",
  "Hi there. Everything feels manageable here, ",
  "Welcome! The pigeon is ready when you are, ",

  "Hello! The pigeon adjusted the rules slightly, ",
  "Welcome back. The raccoon accountant approved the change, ",
  "Hey there. The mouse intern celebrated quietly, ",
  "Welcome! The seagull is temporarily uninterested, ",
  "Hi there. The turtle from HR is satisfied, ",
  "Welcome back. Snacks remain a unifying force, ",
  "Hello! The pigeon believes this is the right moment, ",
  "Welcome! Everything is set up thoughtfully, ",
  "Hey there. The clipboard has no objections, ",
  "Welcome back. The pigeon-verse is stable, ",
];

// 404 quips used by the NotFoundPage; keep tone playful but clear.
export const notfound = [
  "The pigeon checked the map. Then checked it again. This page is not on it.",
  "The mouse ran out of snacks halfway though building this page. The mouse intern is still waiting for their snacks.",
  "The page is missing. The pigeon filed the paperwork immediately.",
  "We asked the pigeon. The pigeon asked the mouse intern. The intern shrugged.",
  "The pigeon opened this door carefully. There was nothing behind it.",
  "According to the pigeon, this page was here earlier. Allegedly.",
  "The pigeon searched high and low. Mostly low. Still no page.",
  "The page is missing. The raccoon accountant says the numbers don’t add up.",
  "The pigeon suspects crumbs are involved. The seagull refuses to comment.",
  "This page took a wrong turn. The pigeon made a note.",
  "The pigeon left a sign here that says ‘Not this way’. Very official.",

  "The mouse intern swears this page existed. The pigeon remains unconvinced.",
  "The pigeon checked the snack drawer first. Force of habit.",
  "This page is absent. The turtle from HR is remaining calm about it.",
  "The pigeon believes this is a navigation issue, not a personal failure.",
  "The owl auditor looked once and said nothing. That was worse.",
  "The pigeon marked this page as ‘missing but polite’.",
  "We searched everywhere. The seagull searched *enthusiastically*. No page.",
  "The pigeon adjusted its tiny tie and apologized professionally.",
  "This page has gone rogue. The pigeon is drafting a policy.",
  "The raccoon accountant insists the page was never budgeted for.",

  "The pigeon retraced every step. The steps did not lead here.",
  "This page is currently unavailable due to being completely gone.",
  "The pigeon believes this page is ‘on a break’.",
  "We asked nicely. The pigeon asked firmly. The page still didn’t return.",
  "The mouse intern labeled this incident ‘educational’.",
  "The pigeon suspects the seagull knows something.",
  "This page is missing. Snack morale has been affected slightly.",
  "The pigeon checked behind the couch. Still nothing.",
  "The turtle from HR says this is ‘one of those things’.",
  "The pigeon filed this under ‘unexpected but manageable’.",

  "The page is not here. The pigeon would like you to know it tried.",
  "This link went on an adventure. The pigeon stayed behind.",
  "The pigeon believes the page took a scenic route and forgot to come back.",
  "We looked everywhere reasonable. The pigeon looked everywhere unreasonable.",
  "The pigeon insists this is not anyone’s fault.",
  "The owl auditor wrote ‘404’ and stared meaningfully.",
  "The pigeon left breadcrumbs. The page did not follow them.",
  "This page is missing. The pigeon recommends returning to safety.",
  "The raccoon accountant says losses are within acceptable limits.",
  "The pigeon says this happens sometimes and it’s okay.",

  "The page is gone. The pigeon is already reorganizing around it.",
  "This is an empty room. The pigeon checked twice.",
  "The pigeon is confident the correct page is nearby.",
  "We found the problem. The page isn’t here.",
  "The mouse intern learned a valuable lesson just now.",
  "The pigeon marked this location ‘non-page’.",
  "The seagull flew by laughing. The pigeon took notes.",
  "This page failed to report for duty.",
  "The pigeon assures you everything else is still in order.",
  "If this page existed, the pigeon would have organized it already.",
];

// Login quips rotate on the login screen to add personality.
export const login = [
  "The pigeon checks the clipboard. You’re on the list.",
  "The pigeon adjusts the badge reader and nods approvingly.",
  "The mouse intern holds the door and whispers ‘they’re cool’.",
  "The pigeon says credentials first, then vibes.",
  "The seagull tried to sneak in earlier. The pigeon remains undefeated.",
  "The turtle from HR reminds everyone there’s no rush.",
  "The pigeon cleared this login space just for you.",
  "The clipboard says ‘expected’. The pigeon agrees.",
  "The mouse intern is watching respectfully.",
  "The pigeon believes this will go smoothly.",

  "The pigeon double-checks the door. It opens politely.",
  "The raccoon accountant confirms access is approved.",
  "The pigeon offers a calm, professional nod.",
  "The mouse intern practiced this moment.",
  "The pigeon says this is the right entrance.",
  "The seagull is not allowed past this point.",
  "The turtle from HR suggests a steady pace.",
  "The pigeon flips the sign from ‘closed’ to ‘welcoming’.",
  "The clipboard is ready when you are.",
  "The pigeon has prepared a dignified silence.",

  "The pigeon recognizes you immediately.",
  "The mouse intern beams. This is exciting.",
  "The pigeon checks once. Then once more. All good.",
  "The raccoon accountant approves the numbers involved.",
  "The pigeon says you’re right on time.",
  "The turtle from HR nods slowly but meaningfully.",
  "The pigeon straightens the entry sign.",
  "The mouse intern whispers encouragement professionally.",
  "The pigeon considers this a routine success.",
  "The clipboard has no objections today.",

  "The pigeon gently gestures toward the login fields.",
  "The mouse intern labels this ‘a big moment’.",
  "The pigeon confirms this is the correct doorway.",
  "The seagull is watching from outside. Jealous.",
  "The turtle from HR says everyone belongs here calmly.",
  "The pigeon checks credentials with care and trust.",
  "The raccoon accountant notes this as ‘authorized’.",
  "The pigeon says access looks good from here.",
  "The mouse intern adjusts their tiny badge.",
  "The pigeon opens the door metaphorically.",

  "The pigeon is pleased to see you return.",
  "The clipboard says this is familiar territory.",
  "The seagull would like you to think that she forgot her keys on purpose",
  "The pigeon verifies calmly, without judgment.",
  "The turtle from HR approves the tone of this moment.",
  "The pigeon marks this as a safe entry point.",
  "The raccoon accountant says everything checks out.",
  "The pigeon believes you belong on the other side of this door.",
  "The mouse intern learned about logins yesterday.",
  "The pigeon is ready when you are.",
];
