import { useState, useEffect } from "react";
import { Key, Copy, Check, Download, Eye, EyeOff, AlertTriangle, Loader2 } from "lucide-react";
import Card from "../cards/Card.jsx";
import Button from "../ui/Button.jsx";
import api from "../../lib/api.js";
import { canUseClipboard, copyWithFeedback } from "../../utils/clipboard";
import { ICON_SIZE } from "@/lib/ui-tokens";

export default function RecoveryKeyCard({ repo, repoId = "" }) {
  const [revealed, setRevealed] = useState(false);
  const [copied, setCopied] = useState(false);
  const [recoveryKey, setRecoveryKey] = useState(repo?.password || "");
  const needsFetch = repoId && !(repo?.password && repo.password !== "autogenerated");
  const [loading, setLoading] = useState(needsFetch);
  const [error, setError] = useState(null);
  const clipboardOk = canUseClipboard();

  useEffect(() => {
    if (!needsFetch) return;
    api(`/backups/repos/${repoId}/recovery-key`)
      .then((res) => res.json())
      .then((data) => {
        setRecoveryKey(data.recovery_key || "");
        setError(null);
      })
      .catch((err) => {
        setError("Could not load recovery key.");
        console.error(err);
      })
      .finally(() => setLoading(false));
  }, [repoId, repo?.password, needsFetch]);

  const handleCopy = () => {
    const key = recoveryKey || repo?.password;
    if (!key || !clipboardOk) return;
    copyWithFeedback(key, setCopied);
  };

  const handleDownload = () => {
    const key = recoveryKey || repo?.password;
    if (!key) return;
    const content = [
      "# LibreServ Recovery Key",
      `# Repository: ${repo?.repo_type || "s3"}://${repo?.repo_path || "unknown"}`,
      `# Saved: ${new Date().toLocaleString()}`,
      "# KEEP THIS FILE SAFE. Without it, you cannot restore your backups.",
      "",
      `RECOVERY_KEY=${key}`,
      `REPO_TYPE=${repo?.repo_type || "s3"}`,
      `REPO_PATH=${repo?.repo_path || "unknown"}`,
    ].join("\n");
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `libreserv-recovery-key-${repo?.id || repoId || "backup"}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const displayKey = recoveryKey || repo?.password;

  return (
    <Card icon={Key} title="Backup Recovery Key" noHeightAnim
      data-slot="recovery-key-card"
      headerActions={
        <span className="text-xs px-2.5 py-1 rounded-pill bg-primary border-2 border-warning/30 text-warning font-medium flex items-center gap-1">
          <AlertTriangle size={ICON_SIZE.xs} />
          Critical
        </span>
      }
    >
      <div className="p-5 space-y-4">
        <p className="text-sm text-accent">
          Your backups are encrypted with a key only this server knows. If you lose access
          to this server, you will need this key to restore your data. Save it somewhere safe —
          <strong className="text-primary"> we cannot recover it for you</strong>.
        </p>

        {loading && (
          <div className="flex items-center gap-2 text-xs text-accent">
            <Loader2 size={ICON_SIZE.sm} className="animate-spin" />
            Loading recovery key...
          </div>
        )}

        {error && (
          <div className="bg-primary text-secondary border-2 border-warning/20 rounded-large-element p-3 text-xs text-accent">
            {error}
          </div>
        )}

        <div className="bg-primary/5 rounded-large-element p-4 space-y-3">
          <p className="text-xs text-accent font-mono">
            {repo?.repo_type || "s3"} → {repo?.repo_path || "Connect Storage"}
          </p>
          <div className="flex items-center gap-2">
            {clipboardOk || !revealed ? (
              <code className="flex-1 text-xs font-mono bg-primary rounded-pill px-4 py-2.5 text-secondary overflow-hidden text-ellipsis whitespace-nowrap border-2 border-secondary/10">
                {revealed ? displayKey || "••••••••••••••••••••••••••" : "••••••••••••••••••••••••••"}
              </code>
            ) : (
              <input
                readOnly
                className="flex-1 text-xs font-mono bg-primary rounded-pill px-4 py-2.5 text-secondary border-2 border-secondary/10"
                value={displayKey || ""}
                onFocus={(e) => e.target.select()}
                aria-label="Recovery key"
              />
            )}
            <Button
              variant="ghost"
              size="icon"
              onClick={() => setRevealed(!revealed)}
              tooltip={revealed ? "Hide key" : "Show key"}
            >
              {revealed ? <EyeOff size={ICON_SIZE.md} /> : <Eye size={ICON_SIZE.md} />}
            </Button>
            {clipboardOk ? (
              <Button
                variant="ghost"
                size="icon"
                onClick={handleCopy}
                tooltip={copied ? "Copied!" : "Copy to clipboard"}
              >
                {copied ? <Check size={ICON_SIZE.md} /> : <Copy size={ICON_SIZE.md} />}
              </Button>
            ) : null}
            <Button
              variant="ghost"
              size="icon"
              onClick={handleDownload}
              tooltip="Download key file"
            >
              <Download size={ICON_SIZE.md} />
            </Button>
          </div>
          {!clipboardOk && revealed && displayKey ? (
            <p className="text-xs text-secondary">
              Select the key above, then copy it.
            </p>
          ) : null}
        </div>

        <div className="bg-primary text-secondary border-2 border-warning/20 rounded-large-element p-4 flex items-start gap-3">
          <AlertTriangle size={ICON_SIZE.lg} className="text-warning shrink-0 mt-0.5" />
          <div className="text-xs text-accent space-y-1">
            <p className="font-medium text-secondary">Without this key:</p>
            <ul className="list-disc list-inside space-y-0.5">
              <li>Your backup data is permanently unrecoverable</li>
              <li>Even LibreServ Connect staff cannot decrypt your backups</li>
              <li>Store this key in a password manager or offline safe</li>
            </ul>
          </div>
        </div>
      </div>
    </Card>
  );
}
