#!/bin/bash
# live-build configuration for the Luna rapidinstall USB.
set -e

lb config noauto \
	--architectures amd64 \
	--distribution bookworm \
	--archive-areas "main contrib non-free non-free-firmware" \
	--parent-mirror-bootstrap http://deb.debian.org/debian \
	--parent-mirror-chroot http://deb.debian.org/debian \
	--linux-packages linux-image \
	--linux-flavours amd64 \
	--firmware-chroot false \
	--firmware-binary false \
	--mode debian \
	--system live \
	--binary-images iso-hybrid \
	--debian-installer false \
	--security false \
	--iso-volume LUNAINST \
	--iso-application "Luna rapidinstall" \
	--bootappend-live "boot=live components quiet splash" \
	--memtest none \
	--win32-loader false \
	--apt-indices false \
	--apt-recommends false \
	"${@}"
