server:
    host: 0.0.0.0
    port: 8080
    mode: development
database:
    path: ./dev/data/libreserv.db
auth:
    jwtsecret: L0AT82XLMFK7B7XnmTN9ulxhfe6kZxsAZhbZRFdExP4=
    secretfile: ""
    csrfsecret: lvuM914vfVditrRDSAHLYxN8DETQjjpy7Cz_HwKQhhk=
apps:
    data_path: ./dev/apps
    catalog_path: ./apps/builtin
docker:
    method: auto
    socketpath: ""
    tcp:
        host: ""
        port: 0
        usetls: false
        certpath: ""
    ssh:
        host: ""
        user: ""
        keypath: ""
    timeout: 30s
logging:
    level: debug
    path: ./dev/logs
network:
    caddy:
        mode: enabled
        adminapi: ""
        configpath: ""
        certspath: ""
        defaultdomain: ""
        email: ""
        autohttps: false
        reload:
            retries: 5
            backoffmin: 0s
            backoffmax: 0s
            jitterfraction: 0
            attempttimeout: 0s
        logging:
            output: stdout
            file: ""
            format: console
            level: ""
    acme:
        external:
            enabled: false
            usedocker: false
            dockerimage: ""
            datapath: ""
            dnsprovider: ""
            dnsenv: {}
            email: ""
            staging: false
            cadirurl: ""
            keytype: ""
            certspath: ""
cors:
    allowedorigins: []
license:
    entitlementfile: ""
    publickeyfile: ""
smtp:
    host: ""
    port: 587
    username: ""
    password: ""
    from: ""
    usetls: false
    skipverify: false
notify:
    enabled: false
    supportrecipients: []
    supportsubject: ""
    supportbody: ""
    welcomesubject: ""
    welcomebody: ""
